// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CBISImpaler.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CBISWriteAPIModelsQueryEditMedia
    {
        /// <summary>
        /// Initializes a new instance of the CBISWriteAPIModelsQueryEditMedia
        /// class.
        /// </summary>
        public CBISWriteAPIModelsQueryEditMedia()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CBISWriteAPIModelsQueryEditMedia
        /// class.
        /// </summary>
        public CBISWriteAPIModelsQueryEditMedia(IList<CBISWriteAPIModelsMedia> set = default(IList<CBISWriteAPIModelsMedia>), IList<string> delete = default(IList<string>))
        {
            Set = set;
            Delete = delete;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Set")]
        public IList<CBISWriteAPIModelsMedia> Set { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Delete")]
        public IList<string> Delete { get; set; }

    }
}
