// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CBISImpaler.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CBISWriteAPIModelsQueryEditOccasion
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CBISWriteAPIModelsQueryEditOccasion class.
        /// </summary>
        public CBISWriteAPIModelsQueryEditOccasion()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// CBISWriteAPIModelsQueryEditOccasion class.
        /// </summary>
        public CBISWriteAPIModelsQueryEditOccasion(IList<CBISWriteAPIModelsOccasion> set = default(IList<CBISWriteAPIModelsOccasion>), IList<CBISWriteAPIModelsOccasion> delete = default(IList<CBISWriteAPIModelsOccasion>))
        {
            Set = set;
            Delete = delete;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Set")]
        public IList<CBISWriteAPIModelsOccasion> Set { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Delete")]
        public IList<CBISWriteAPIModelsOccasion> Delete { get; set; }

    }
}
