// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CBISimpaler.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CBISWriteAPIModelsOccasion
    {
        /// <summary>
        /// Initializes a new instance of the CBISWriteAPIModelsOccasion class.
        /// </summary>
        public CBISWriteAPIModelsOccasion()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CBISWriteAPIModelsOccasion class.
        /// </summary>
        public CBISWriteAPIModelsOccasion(System.DateTime? end = default(System.DateTime?), string duration = default(string), string startTime = default(string), System.DateTime? start = default(System.DateTime?), int? arena = default(int?), bool? monday = default(bool?), bool? tuesday = default(bool?), bool? wednesday = default(bool?), bool? thursday = default(bool?), bool? friday = default(bool?), bool? saturday = default(bool?), bool? sunday = default(bool?))
        {
            End = end;
            Duration = duration;
            StartTime = startTime;
            Start = start;
            Arena = arena;
            Monday = monday;
            Tuesday = tuesday;
            Wednesday = wednesday;
            Thursday = thursday;
            Friday = friday;
            Saturday = saturday;
            Sunday = sunday;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "End")]
        public System.DateTime? End { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Duration")]
        public string Duration { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StartTime")]
        public string StartTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Start")]
        public System.DateTime? Start { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Arena")]
        public int? Arena { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Monday")]
        public bool? Monday { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Tuesday")]
        public bool? Tuesday { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Wednesday")]
        public bool? Wednesday { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Thursday")]
        public bool? Thursday { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Friday")]
        public bool? Friday { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Saturday")]
        public bool? Saturday { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Sunday")]
        public bool? Sunday { get; set; }

    }
}
