// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CBISimpaler.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CBISWriteAPIModelsMedia
    {
        /// <summary>
        /// Initializes a new instance of the CBISWriteAPIModelsMedia class.
        /// </summary>
        public CBISWriteAPIModelsMedia()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CBISWriteAPIModelsMedia class.
        /// </summary>
        /// <param name="type">Possible values include: 'Image',
        /// 'Video'</param>
        /// <param name="externalReference">Media external reference, used for
        /// deletion (default: Location)</param>
        public CBISWriteAPIModelsMedia(string location = default(string), string type = default(string), bool? isMainMedia = default(bool?), string externalReference = default(string), string copyrightBy = default(string), string fileName = default(string), string producedBy = default(string), IList<CBISWriteAPIModelsMediaTranslation> translations = default(IList<CBISWriteAPIModelsMediaTranslation>))
        {
            Location = location;
            Type = type;
            IsMainMedia = isMainMedia;
            ExternalReference = externalReference;
            CopyrightBy = copyrightBy;
            FileName = fileName;
            ProducedBy = producedBy;
            Translations = translations;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Location")]
        public string Location { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Image', 'Video'
        /// </summary>
        [JsonProperty(PropertyName = "Type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "IsMainMedia")]
        public bool? IsMainMedia { get; set; }

        /// <summary>
        /// Gets or sets media external reference, used for deletion (default:
        /// Location)
        /// </summary>
        [JsonProperty(PropertyName = "ExternalReference")]
        public string ExternalReference { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "CopyrightBy")]
        public string CopyrightBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "FileName")]
        public string FileName { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ProducedBy")]
        public string ProducedBy { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Translations")]
        public IList<CBISWriteAPIModelsMediaTranslation> Translations { get; set; }

    }
}
