// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CBISImpaler.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CBISWriteAPIModelsQueryEditReference
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CBISWriteAPIModelsQueryEditReference class.
        /// </summary>
        public CBISWriteAPIModelsQueryEditReference()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// CBISWriteAPIModelsQueryEditReference class.
        /// </summary>
        public CBISWriteAPIModelsQueryEditReference(IList<CBISWriteAPIModelsProductReference> set = default(IList<CBISWriteAPIModelsProductReference>), IList<CBISWriteAPIModelsProductReference> delete = default(IList<CBISWriteAPIModelsProductReference>))
        {
            Set = set;
            Delete = delete;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Set")]
        public IList<CBISWriteAPIModelsProductReference> Set { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Delete")]
        public IList<CBISWriteAPIModelsProductReference> Delete { get; set; }

    }
}
