// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CBISimpaler.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CBISWriteAPIModelsInformationKey
    {
        /// <summary>
        /// Initializes a new instance of the CBISWriteAPIModelsInformationKey
        /// class.
        /// </summary>
        public CBISWriteAPIModelsInformationKey()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CBISWriteAPIModelsInformationKey
        /// class.
        /// </summary>
        public CBISWriteAPIModelsInformationKey(int? attributeId = default(int?), string culture = default(string))
        {
            AttributeId = attributeId;
            Culture = culture;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "AttributeId")]
        public int? AttributeId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Culture")]
        public string Culture { get; set; }

    }
}
