// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace CBISimpaler.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CBISWriteAPIModelsInformation
    {
        /// <summary>
        /// Initializes a new instance of the CBISWriteAPIModelsInformation
        /// class.
        /// </summary>
        public CBISWriteAPIModelsInformation()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CBISWriteAPIModelsInformation
        /// class.
        /// </summary>
        public CBISWriteAPIModelsInformation(CBISWriteAPIModelsInformationKey attribute = default(CBISWriteAPIModelsInformationKey), string value = default(string))
        {
            Attribute = attribute;
            Value = value;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Attribute")]
        public CBISWriteAPIModelsInformationKey Attribute { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Value")]
        public string Value { get; set; }

    }
}
